### ISSUE TITLE
Client sometimes crashes with `Error openen map file`

### ISSUE THREAD

**Issue by KeyboardInterrupt** [AlbianWarp/AlbianWarpClient#17]
![image](https://user-images.githubusercontent.com/26553592/38970875-4c8c6b6e-4398-11e8-94dd-3c06375e4fa6.png)

Sometimes the Client cannot open the Shared Memory Interface and crashes, we should try to find out what causes this...

**Comment by Amaikokonut** [comment]
This problem happens a lot to me during testing-- usually after a bunch of other CAOS-errors are thrown/autokilled because I am butchering everything. In my experience there doesn't seem to be a specific cause other than other 'things going horribly wrong'. _Hopefully_ if we can correct those underlying issues, this will go away, but if we can narrow down anything specific, all the better.

**Comment by KeyboardInterrupt** [comment]
@Amaikokonut  Have you seen this one recently?
I have not stumbled upon it that much recently.
If there is no good way to reproduce this Issue, We should not prioritize it to much.
When we find a reliable way to trigger this Bug, I will take a look at it again.

**Comment by Amaikokonut** [comment]
Yeah pretty much the only time I get this is when I am testing and something gets out of control from the CAOS side of things (brutal ignoring multiple caos errors for instance). I don't think this is a bug in and of itself as much as it is a symptom of problems with the CAOS. I haven't got this error in the course of normal gameplay in quite some time so I agree that it's not really worth priority right now.

**Comment by KeyboardInterrupt** [comment]
This is made obsolete by the Switch to ReBabel
