### ISSUE TITLE
Specification of SystemMessageAgent system

### ISSUE THREAD

**Issue by KeyboardInterrupt** [AlbianWarp/AlbianWarpClient#32]
Scope of this issue is to internally discuss how SMA's could be implemented, what they should be used for and what they should not be used for.

I think we will eventually need another Agent type for System/Albianwarp Messages, like:

- Errors
- Update Notifications
- Dialog Boxes (for user feedback)
  - Yes/No

SMA's are probably only exchanged between the Client and the game, and the Server itself, they are not sent from one Player to another. (Thats what RTDMA's and regular DMA's are for)

**Comment by Amaikokonut** [comment]
Since one-way messages from the client to the engine are generally faster to just mesg-writ in, I think of SMAs as being used mostly by the engine to ask the client/server to do something or to let them know something. Things like:

- I clicked the button to go offline, so please stop sending/recieving DMAs/creatures/etc and wait until I ask to go online again.
- I clicked the button to go online, so please resume those things
- I need to know how long the server has been up
- I need to know if there are any creatures still pending upload
- Here is the answer to a question you asked me (for dialogue boxes that would be mesg-writ'd in)
etc

**Comment by Amaikokonut** [comment]
Hmm, this could also be used to let the client know when there are problems warping in or out certain creatures due to them already existing on disk, so the client can move those creatures into a "duplicates" subfolder or something.

**Comment by KeyboardInterrupt** [comment]
This is made obsolete by the Switch to ReBabel
