### ISSUE TITLE
Expanding DMAs/RTMDAs to include a mesg-writ function?

### ISSUE THREAD

**Issue by Amaikokonut** [AlbianWarp/AlbianWarpClient#37]
This is related to #36 but is kind of it's own thing. If the client could mesg writ the engine after injecting RT/DMAs, it would save a lot of resources on the engine's part since it wouldn't have to have scripts that constantly check for new RT/DMAs and slow things down. This might become quite an issue once a lot of warp-reliant agents are being developed.

I propose that an RTD/MA could have two optional variables, called **"aw_target_agent"** and **"aw_target_script"**.
**"aw_target_agent"** would be a string corresponding to a game variable that holds an agent, for example "aw_housekeeper_agent" or "aw_immigrant_checker". **"aw_target_script"** would hold the script number that would be messaged. 

There would have to be a way to 'whitelist' scripts so people aren't sending DMAs to any agent's scripts just to force someone's game to execute them. I propose that if an agent wanted to be set up to receive mesg-writs from the client, it would have to:
- Set a GAME variable to itself, the variable name being the same as the one that would be specified as the **"aw_target_agent"** in the DMA (such as "aw_immigrant_checker" etc)
- Set (to 1) a name variable on itself named "allow_#" wherein # is the script number that is allowed to be triggered via an RT/DMA.

**Example:**

A mail message DMA is created:
"aw_recipient" = "bob"
"aw_target_agent" = "aw_mailman_agent"
"aw_target_script" = 1005
"some_other_vars" = "some other content"

- The sender's client picks up the message and sends it to bob.
- Bob's client injects the DMA.
- Bobs client then checks to see if GAME "aw_mailman_agent" actually exists and is a valid agent.
- If it is, it TARGs the agent and checks if NAME "allow_1005" equals 1. 
- If it does, the client goes ahead and mesg writ's the agent with script 1005.
- Script 1005 goes off and checks for DMAs, doing whatever it does with them.

Does this seem like a viable thing to consider for future development?

**Comment by KeyboardInterrupt** [comment]
This is a really great Idea!

What if we allowed Agents to register them self in the registry via SMA's, The registry could be used to associate the `aw_target_agent` String with the Agent ID to target.
This could then be used by thirds party developer to register their own Agents as possible targets.
This would also allow to register multiple agents of the same type with different names like:
`warp_ball_toy_01`, `warp_ball_toy_02`, `warp_ball_toy_03` each being another Agent/Toy.

To avoid accidental mischief by overwriting names we could issue an interactive Prompt asking the player if it wants to re/register the Agent. but on the other hand, this wont stop truly bad intent, as there is no protected CAOS or whatever ^^.

But can we make these new variables optional? what happens if we omit them? What is the default behavior?

**Comment by Amaikokonut** [comment]
I think if those new variables are omitted, the client will just behave as it does now-- inject the RT/DMA and let another script worry about picking it up and scanning it. Probably not every developer will want to use this system.

Do you think using SMAs to tell the client which agents/scripts are target-able would be better than just using GAME/NAME variables? I am concerned about things like if the client closes or crashes, would the agents need to re-register themselves? How would they know to do that? What if they need to "unregister"? I feel like it might be easier to check for those variable flags in the engine's game/name vars, since those are simple to change already.

**Comment by KeyboardInterrupt** [comment]
This is made obsolete by the Switch to ReBabel
